### ISSUE TITLE
Fix AgragationDef in queries

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#163]
Assuming the following schema:
```scala
val customers = (uuid("id") ++ localDate("dob") ++ string("first_name") ++ string("last_name")).table("customers")
val customerId :*: dob :*: fName :*: lName :*: _ = customers.columns
```
when running the following query:
```scala
select { Count(customerId) } from customers
//renders to: SELECT count(customers.id) FROM customers
```
it fails with:
```
java.lang.IllegalArgumentException: Invalid UUID string: 5
[info]          at java.util.UUID.fromString(UUID.java:194)
[info]          at zio.sql.Jdbc$ReadExecutor$.$anonfun$extractColumn$51(jdbc.scala:194)
[info]          at zio.sql.Jdbc$ReadExecutor$.tryDecode$1(jdbc.scala:150)
[info]          at zio.sql.Jdbc$ReadExecutor$.extractColumn(jdbc.scala:193)
[info]          at zio.sql.Jdbc$ReadExecutor$.$anonfun$unsafeExtractRow$1(jdbc.scala:223)
[info]          at scala.collection.IndexedSeqOps.foldRight(IndexedSeq.scala:63)
[info]          at scala.collection.IndexedSeqOps.foldRight$(IndexedSeq.scala:59)
[info]          at scala.collection.immutable.Vector.foldRight(Vector.scala:113)
[info]          at zio.sql.Jdbc$ReadExecutor$.unsafeExtractRow(jdbc.scala:220)
[info]          at zio.sql.Jdbc$ReadExecutor$$anon$2.$anonfun$execute$4(jdbc.scala:86)
[info]          at zio.stream.ZStream$.$anonfun$unfoldM$1(ZStream.scala:3908)
[info]          at zio.internal.FiberContext.evaluateNow(FiberContext.scala:351)
[info]          at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:778)
[info]          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]          at java.lang.Thread.run(Thread.java:748)
```
Probable cause: ReadExecutor is trying to interpret the result of the AggregationDef as the type of the aggregated column.

**Comment by sviezypan** [comment]
```
      val query = select { Count(customerId) } from customers

      assertM(execute(query).runHead.some)(equalTo(4L)
```
Test passes for postgres module.
