### ISSUE TITLE
Testcontainers not closing correctly after tests

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#666]
When running the tests from `sbt` with:
```
sbt test
```
some of the containers don't close after running the tests finish. Resulting in:
![testcontainers](https://user-images.githubusercontent.com/1301520/170470001-ee05402f-56ef-4a5f-80d7-f4c99b1c9e05.png)

Perhaps there's a problem with how `zio.sql.TestContainer` and `zio.sql.JdbcRunnableSpec` are interacting with ZIO Test.

**Comment by kyledinh** [comment]
I pull the latest from master today, and was able to run the test and it clean up the containers afterwards:

```
*[master][~/src/github.com/zio/zio-sql]$ docker stats --no-stream
CONTAINER ID   NAME                                                       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O       PIDS
0075ff73a50e   jolly_robinson                                             0.70%     289.1MiB / 19.55GiB   1.44%     5.88kB / 3.7kB    115kB / 299MB   39
d1799132808a   affectionate_galileo                                       0.76%     289.2MiB / 19.55GiB   1.44%     6.85kB / 4.34kB   115kB / 301MB   39
6296273ee3e0   objective_kare                                             0.50%     291.3MiB / 19.55GiB   1.45%     7.78kB / 4.93kB   115kB / 298MB   40
45a17d507daa   pensive_wiles                                              0.59%     289.9MiB / 19.55GiB   1.45%     8.61kB / 5.46kB   115kB / 301MB   39
2bb6686069f7   quizzical_meninsky                                         0.82%     289MiB / 19.55GiB     1.44%     11.8kB / 7.45kB   131kB / 302MB   39
3c12a3991a6a   testcontainers-ryuk-5a9f063b-5a96-42cc-a4a3-e585b14270d8   0.00%     2.93MiB / 19.55GiB    0.01%     2.97kB / 990B     16.4kB / 0B     6
f03ca6ab4111   nifty_black                                                0.63%     353.4MiB / 19.55GiB   1.77%     24kB / 16kB       79MB / 294MB    39
095bff5566ba   testcontainers-ryuk-1ef7ed65-5e5f-4bb4-976a-8197e69ba965   0.00%     2.891MiB / 19.55GiB   0.01%     3.66kB / 1.03kB   0B / 0B         6
ff94824953d0   testcontainers-ryuk-277f5792-f671-498c-b3be-c20e1ef3fb72   0.00%     2.785MiB / 19.55GiB   0.01%     3.9kB / 1.03kB    69.6kB / 0B     6
323924df034b   testcontainers-ryuk-da726ecf-2a8c-4dfb-8cca-e0418d24036a   0.00%     2.906MiB / 19.55GiB   0.01%     4.01kB / 1.1kB    5.35MB / 0B     5

*[master][~/src/github.com/zio/zio-sql]$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
*[master][~/src/github.com/zio/zio-sql]$ 
```

All test passed, except this `setseed` and a warning:

```
...
  + factorial
02:36:07.738 [zio-default-blocking-2] INFO  🐳 [mysql:latest] - Container mysql:latest is starting: 45a17d507daabd0695b05806f73f99e89f02d3d8251279bb2ef31f309be4f4d3
  + lpad
  - setseed
    ✗ Tuple2(
        _1 = 0.8938509552989213,
        _2 = 0.967951085560987
      ) was not equal to Tuple2(
        _1 = 0.019967750719779076,
        _2 = 0.8378369929936333
      )
    <CODE>
    input = Tuple2(
      _1 = 0.8938509552989213,
      _2 = 0.967951085560987
    )
    at /Users/kyle/src/github.com/zio/zio-sql/postgres/src/test/scala/zio/sql/postgresql/CustomFunctionDefSpec.scala:577

  + rpad
  + to_timestamp
  
... 

[warn] In the last 10 seconds, 5.629 (61.2%) were spent in GC. [Heap: 0.01GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
Exception in thread "classloader-cache-cleanup-0" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space25s
[warn] In the last 10 seconds, 87.484 (950.5%) were spent in GC. [Heap: 0.01GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
	at java.base/java.util.LinkedHashMap.newNode(LinkedHashMap.java:257)
  | => zat java.base/java.util.HashMap.putVal(HashMap.java:640)
  | => zat java.base/java.util.HashMap.put(HashMap.java:610)
  | => zat org.testcontainers.shaded.com.fasterxml.jackson.databind.node.ObjectNode.replace(ObjectNode.java:420)
  | => zat org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
  | => zat org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
  | => zat org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
  | => oat org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)
  | => sat org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2207)
	at org.testcontainers.shaded.com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1680)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerObjectDeserializer.deserialize(DockerClientConfig.java:130)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:75)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:52)
	at org.testcontainers.containers.ContainerState.getCurrentContainerInfo(ContainerState.java:123)
	at org.testcontainers.containers.ContainerState.isRunning(ContainerState.java:76)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:230)
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:159)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.testcontainers.containers.GenericContainer$$Lambda$14125/0x0000000802f7c8e0.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
	at zio.sql.JdbcRunnableSpec.$anonfun$testContainer$2(JdbcRunnableSpec.scala:73)
	at zio.sql.JdbcRunnableSpec$$Lambda$14061/0x0000000802e664e0.apply(Unknown Source)
sbt test  517.93s user 18.76s system 352% cpu 2:32.26 total
*[master][~/src/github.com/zio/zio-sql]$ 
```

**Comment by kyledinh** [comment]
I pulled the latest and ran the test and the containers are cleaning themselves afterwards:

```
    + lower
    + trim
37 tests passed. 0 tests failed. 1 tests ignored.

Executed in 7 m 16 s

[info] Completed tests
[error] (postgres / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 296 s (04:56), completed Oct 28, 2022, 3:08:38 AM
sbt test  295.43s user 20.04s system 103% cpu 5:03.57 total
*[master][~/src/github.com/zio/zio-sql]$ docker ps                                                        
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
*[master][~/src/github.com/zio/zio-sql]$ 
```

I was getting this error with the default sbt settings:
```
[error] ## Exception when compiling 4 sources to /Users/kyle/src/github.com/zio/zio-sql/sqlserver/target/scala-2.13/test-classes
[error] java.lang.OutOfMemoryError: Java heap space
[error] 
[error]            
+ Hikaricp module
java.lang.OutOfMemoryError: Java heap space
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space
```

Solved it with:
- https://support.snyk.io/hc/en-us/articles/360003143417-Out-of-Memory-Error-when-testing-Scala-sbt-project
```
export SBT_OPTS="-Xms1024M -Xmx4G -Xss2M -XX:MaxMetaspaceSize=2G"
```
